#!/bin/bash
# REKALL Auto-Fix — Incident e5c64057-4671-442d-b1ab-66b68c1610b2
# Tier: T1_human
# Generated by REKALL AI agent pipeline (human-approved)

echo 'Applying fix: API key or secret token detected in commit history or log output. Rotate the credential immediately, scrub from git history, and move to a secrets manager.'

git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch .env' HEAD
git push origin --force --all
# Rotate the exposed credential in your secrets manager
kubectl create secret generic api-credentials --from-literal=API_KEY=<new-key> --dry-run=client -o yaml | kubectl apply -f -
